export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKET = "GET_TICKET";
export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const UNSET_TICKET = "UNSET_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const GET_TICKET_TYPES = "GET_TICKET_TYPE";
export const GET_TICKET_SUBTYPES = "GET_TICKET_SUBTYPE";
export const UNSET_TICKET_SUBTYPES = "UNSET_TICKET_SUBTYPES";
export const GET_TICKET_STATUS = "GET_TICKET_STATUS";
export const SEND_TICKET_MESSAGE = "SEND_TICKET_MESSAGE";
export const GET_TICKET_MESSAGES = "GET_TICKET_MESSAGES";
export const CLOSE_TICKET = "CLOSE_TICKET";
export const CANCEL_TICKET = "CANCEL_TICKET";
export const PROCEED_TICKET = "PROCEED_TICKET";
export const LOADING_TICKET = "LOADING_TICKET";
export const UNSET_TICKET_MESSAGES = "UNSET_TICKET_MESSAGES";

export const GET_LINGO_PLANS = "GET_LINGO_PLANS";
export const GET_LINGO_CLASS_TIMES = "GET_LINGO_CLASS_TIMES";
export const GET_LINGO_TOOLS = "GET_LINGO_TOOLS";
export const GET_LINGO_LANGUAGES = "GET_LINGO_LANGUAGES";
export const GET_LINGO_ALL_COUNTRIES = "GET_LINGO_ALL_COUNTRIES";
export const GET_LINGO_ECONOMIC_GROUPS = "GET_LINGO_ECONOMIC_GROUPS";
export const GET_LINGO_LEVELS = "GET_LINGO_LEVELS";
export const GET_LINGO_ALL_LANGUAGES = "GET_LINGO_ALL_LANGUAGES";
export const GET_LINGO_ECONOMIC_GROUPS_COMPANYS = "GET_LINGO_ECONOMIC_GROUPS_COMPANYS";
export const GET_LINGO_RATING_CRITERIAS = "GET_LINGO_RATING_CRITERIAS";

export const GET_TEACHERS = "GET_TEACHERS";
export const UNSET_TEACHER = "UNSET_TEACHER";
export const GET_TEACHER = "GET_TEACHER";
export const ADD_TEACHER = "ADD_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";
export const UPDATE_TEACHER = "DELETE_TEACHER";

export const GET_COUPONS = "GET_COUPONS";
export const GET_COUPON = "GET_COUPON";
export const ADD_COUPON = "ADD_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const UNSET_COUPON = "UNSET_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON"
export const SET_COUPON_ERROR = "SET_COUPON_ERROR";
export const UNSET_COUPON_ERROR = "UNSET_COUPON_ERROR";

export const GET_DEMOCLASSES = "GET_DEMOCLASSES";
export const GET_DEMOCLASS = "GET_DEMOCLASS";
export const ADD_DEMOCLASS = "ADD_DEMOCLASS";
export const SEND_DEMOCLASS_MESSAGE = "SEND_DEMOCLASS_MESSAGE";
export const UNSET_DEMOCLASS = "UNSET_DEMOCLASS";
export const UPDATE_DEMOCLASS = "UPDATE_DEMOCLASS";
export const GET_DEMOCLASS_MESSAGES = "GET_DEMOCLASS_MESSAGES";
export const LOADING_DEMOCLASS = "LOADING_DEMOCLASS";
export const SET_DEMOCLASS_ERROR = "SET_DEMOCLASS_ERROR";
export const UNSET_DEMOCLASS_ERROR = "UNSET_DEMOCLASS_ERROR";
export const SET_DEMOCLASS_SUCCESS = "SET_DEMOCLASS_SUCCESS";
export const UNSET_DEMOCLASS_SUCCESS = "UNSET_DEMOCLASS_SUCCESS";
export const UNSET_DEMOCLASS_LOADING = "UNSET_DEMOCLASS_LOADING";

export const GET_COORDINATORS = "GET_COORDINATORS";
export const GET_COORDINATOR = "GET_COORDINATOR";

export const GET_USER_NOTIFICATIONS = "GET_USER_NOTIFICATIONS";
export const GET_LINGO_NOTIFICATIONS = "GET_LINGO_NOTIFICATIONS";
export const SET_NOTIFICATION_LOADING = "SET_NOTIFICATION_LOADING";
export const SET_NOTIFICATION_SUCCESS = "SET_NOTIFICATION_SUCCESS";
export const SET_NOTIFICATION_MESSAGE = "SET_NOTIFICATION_MESSAGE";
export const UNSET_NOTIFICATION_LOADING = "UNSET_NOTIFICATION_LOADING";
export const UNSET_NOTIFICATION_SUCCESS = "UNSET_NOTIFICATION_SUCCESS";
export const UNSET_NOTIFICATION_MESSAGE = "UNSET_NOTIFICATION_MESSAGE";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_PLANS = "GET_USER_PLANS";
export const GET_AVERAGE_RATING = "GET_AVERAGE_RATING";
export const GET_NEXT_CLASSES = "GET_NEXT_CLASSES";
export const GET_REQUESTED_CLASSES = "GET_REQUESTED_CLASSES";
export const GET_LIST_SEQUENTIAL_CLASSES = "GET_LIST_SEQUENTIAL_CLASSES";

export const GET_CALENDAR_CLASSES = "GET_CALENDAR_CLASSES"
export const SET_CALENDAR_LOADING = "SET_CALENDAR_LOADING";
export const UNSET_CALENDAR_LOADING = "UNSET_CALENDAR_LOADING";
export const GET_CLASSES_FOR_RATING = "GET_CLASSES_FOR_RATING";
export const UNSET_CLASSES_FOR_RATING = "UNSET_CLASSES_FOR_RATING";
export const SET_CLASSES_FOR_RATING = "SET_CLASSES_FOR_RATING";
export const SET_CALENDAR_SCREEN = "SET_CALENDAR_SCREEN";
export const SET_CALENDAR_INITIAL_PARAMS = "SET_CALENDAR_INITIAL_PARAMS";
export const APPLY_CALENDAR_FILTERS = "APPLY_CALENDAR_FILTERS";

